workspace:
  base: /go
  path: src/github.com/drone/drone-cli

pipeline:
  build:
    image: golang:1.9
    commands: sh .drone.sh

  snapshot:
    image: plugins/docker
    repo: drone/cli
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: push

  release:
    image: plugins/github-release
    files:
      - release/drone_*.tar.gz
      - release/drone_checksums.txt
    secrets:
      - source: github_token
        target: github_release_api_key
    when:
      event: tag
